# Generated by Django 3.2.5 on 2021-08-02 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=22)),
                ('Last_name', models.CharField(max_length=22)),
                ('Gender', models.CharField(max_length=22)),
                ('Age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(103)])),
                ('Disease', models.CharField(max_length=220)),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Doctor_fees', models.IntegerField(default=500)),
                ('Med_date', models.DateField()),
            ],
        ),
    ]
